# Generated by Django 4.2.6 on 2023-10-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0002_remove_reply_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='problem_num',
            field=models.IntegerField(null=True),
        ),
    ]
