# Generated by Django 4.2.6 on 2023-10-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0003_reply_problem_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='updated_at',
        ),
    ]
