# Generated by Django 4.2.7 on 2023-11-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_products',
            field=models.ManyToManyField(related_name='registered_users', to='interests.product'),
        ),
    ]
