# Generated by Django 4.2.7 on 2023-11-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
        ('accounts', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='registered_products',
        ),
        migrations.AddField(
            model_name='user',
            name='registered_products',
            field=models.ManyToManyField(related_name='registering_users', to='interests.product'),
        ),
    ]
