# Generated by Django 4.2.7 on 2023-11-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_age_user_money_user_nickname_user_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
