# Generated by Django 4.2.7 on 2023-11-22 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0002_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='dcls_month',
        ),
        migrations.RemoveField(
            model_name='option',
            name='fin_co_no',
        ),
        migrations.RemoveField(
            model_name='option',
            name='fin_prdt_cd',
        ),
        migrations.RemoveField(
            model_name='option',
            name='intr_rate_type_nm',
        ),
    ]
