# Generated by Django 4.2.7 on 2023-11-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0003_remove_option_dcls_month_remove_option_fin_co_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='intr_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='intr_rate2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
